// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eogutojmiggkmrbjebwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvZ3V0b2ptaWdna21yYmplYndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI2MDIsImV4cCI6MjA2NTQ4ODYwMn0.oKKJymLHShVSuMF6C6QjpKXvau7cT_2KvXzyyCshCek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);